// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/homepage-variants/DealFlow.tsx": () => import("../components/mockups/homepage-variants/DealFlow.tsx"),
  "./components/mockups/homepage-variants/Premium.tsx": () => import("../components/mockups/homepage-variants/Premium.tsx")
};
